Fix runtime error related to `wrap`
This inlines the use of wrap. Therefore we have to keep a reference to the original function, which we save in a new attribute.
Even if the code was called multiple times, the `hasattr` check ensures that we don't overwrite the reference with our own function (which would create a cycle)

Before when running the plugin the following exception occured:
```Caught exception:
Traceback (most recent call last):
  File "decorator", line 231, in fun
  File "decorator", line 203, in fix
  File "inspect", line 3045, in bind
  File "inspect", line 2966, in _bind
TypeError: too many positional arguments
```